[limits]
MAX_FUNCTION = 10
MAX_METHOD_BY_STRUCT = 3
MAX_GLOBAL_VARIABLES = 10
MAX_OPERATION_DEPTH = 5
MAX_COMPOSITE_DEPTH = 2
MAX_COMPOSITE_SIZE = 10
MAX_INSTRUCTION_DEPTH = 5
MAX_INSTRUCTION_BY_FUNCTION = 50
MAX_INSTRUCTION_BY_LAMBDA = 10
MAX_INSTRUCTION_BY_METHOD = 20
MAX_FUNCTION_ARGUMENTS = 5
MAX_LAMBDA_ARGUMENTS = 3
MAX_METHOD_ARGUMENTS = 3
MAX_STRUCT = 10
MAX_LOOP_IN_FOR = 10
MIN_DATA_LENGTH = 100000
MAX_DATA_LENGTH = 10000000
USE_OF_SLICE = 1