[package]
name = "noir_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
rand_core = "*"
rand_xorshift = "*"
lazy_static = "*"
backtrace = "0.3.54"
timeout-readwrite = "*"
tokio = { version = "1", features = ["full"] }
regex = "1.5.4"

[profile.dev]
debug = true

[profile.release]
debug = true

