[package]
name = "generic_hash_to_field"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
honggfuzz = "*"
blake2 = "*"
acir = { path = "../../../acvm/acir" }